- include_vars:
    file: site_settings.yml
    name: site_settings


- win_chocolatey:
    name: "{{ item.name }}"
    params: "{{ item.params|default('') }}"
    timeout: 5400
  with_items:
    - name: python3
    - name: git
      params: '"/GitAndUnixToolsOnPath"'
    - name: visualstudio2017community
    - name: visualstudio2017-workload-nativedesktop
      params: "--includeOptional"
    - name: microsoft-visual-cpp-build-tools


- name: install pypiwin32
  win_shell: py -3 -m pip install pypiwin32
  args:
    creates: C:\Python36\Scripts\pywin32_postinstall.py
  notify: pywin32 installed

- name: Ensure that winpy wintypes36.dll is in PATH
  win_path:
    elements:
      - 'C:\Python36\Lib\site-packages\pypiwin32_system32'
      - 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin'


- name: setup buildbot-worker user
  win_user:
    name: buildbot-worker
    password: "{{ vault_windows_worker_password }}"
    password_never_expires: yes
    user_cannot_change_password: yes


- name: add account to Log on as a service
  win_user_right:
    name: SeServiceLogonRight
    users:
    - '.\buildbot-worker'
    action: add


- name: install buildbot-worker
  win_shell: py -3 -m pip install buildbot-worker
  args:
    creates: C:\Python36\Scripts\buildbot-worker.exe


- name: create workspace for the buildbot worker
  become: yes
  become_user: buildbot-worker
  win_shell:
    py -3 C:\Python36\Scripts\buildbot-worker.exe create-worker
      C:\BuildbotWorker
      "{{hostvars[groups['master'][0]]['ec2_private_ip_address']}}"
      windows_server_2016
      "{{site_settings.worker_pass}}"
  args:
    creates: C:\BuildbotWorker


- name: create the BuildResources directory
  win_file:
    path: 'C:\BuildResources'
    state: directory


# wheel mirrored from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pywin32
- name: download resources for the build tasks
  win_get_url:
    url: 'https://s3.amazonaws.com/golem-buildbot-build-resources/pywin32-221-cp36-cp36m-win_amd64.whl'
    dest: 'C:\BuildResources\pywin32-221-cp36-cp36m-win_amd64.whl'
    force: no


- name: check if hyperg installed
  win_stat:
    path: C:\BuildResources\hyperg
  register: hyperg_exists


- name: download hyperg for the build tasks
  win_get_url:
    url: https://github.com/mfranciszkiewicz/golem-hyperdrive/releases/download/v0.2.3/hyperg_0.2.3_windows-x64.zip
    dest: C:\BuildResources\hyperg_0.2.3_windows-x64.zip
    force: no
  when: not hyperg_exists.stat.exists


- name: unzip hyperg for the build tasks
  win_unzip:
    src: C:\BuildResources\hyperg_0.2.3_windows-x64.zip
    dest: C:\BuildResources
    delete_archive: yes
  when: not hyperg_exists.stat.exists


- name: check if geth installed
  win_stat:
    path: C:\BuildResources\geth-windows-amd64-1.7.2-1db4ecdc
  register: geth_exists


- name: download geth for the build tasks
  win_get_url:
    url: https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.7.2-1db4ecdc.zip
    dest: C:\BuildResources\geth-windows-amd64-1.7.2-1db4ecdc.zip
    force: no
  when: not geth_exists.stat.exists


- name: unzip geth for the build tasks
  win_unzip:
    src: C:\BuildResources\geth-windows-amd64-1.7.2-1db4ecdc.zip
    dest: C:\BuildResources
    delete_archive: yes
  when: not geth_exists.stat.exists


- name: check if service is created
  win_shell: Get-Service -Name BuildBot -ErrorAction SilentlyContinue
  register: service_exists
  ignore_errors: yes


- name: create service for the buildbot worker
  win_shell:
    py -3 C:\Python36\Scripts\buildbot_worker_windows_service.exe
      --user .\buildbot-worker
      --password
      "{{ vault_windows_worker_password }}"
      --startup delayed
      install
  when: service_exists.rc == 1


- name: check if worker started once
  become: yes
  become_user: buildbot-worker
  ignore_errors: yes
  win_stat:
    path: C:\BuildbotWorker\twistd.log
  register: log_exists


- name: Start worker for first time
  become: yes
  become_user: buildbot-worker
  win_shell:
    Start-Process C:\Python36\Scripts\buildbot-worker.exe -ArgumentList "start","C:\BuildbotWorker"
  when: not log_exists.exception and not log_exists.stat.exists

- pause:
    seconds: 10
  when: not log_exists.exception and not log_exists.stat.exists


- name: Stop worker for first time
  become: yes
  become_user: buildbot-worker
  win_shell:
    Stop-Process -name buildbot-worker
  when: not log_exists.exception and not log_exists.stat.exists


- name: set registry key right
  win_acl:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\BuildBot
    user: .\buildbot-worker
    rights: FullControl
    type: allow
    state: present
    inherit: ContainerInherit, ObjectInherit
    propagation: 'None'


- name: Create registry path BuildBot
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\services\BuildBot


- name: Create registry path BuildBot\Parameters
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\services\BuildBot\Parameters


- name: Add buildbot worker folder to registry
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\services\BuildBot\Parameters
    name: directories
    data: C:\BuildbotWorker
    type: String


- name: start service
  win_service:
    name: BuildBot
    start_mode: delayed
    state: started
