- name: reconfigure buildbot
  become: yes
  become_user: buildbot
  shell: /var/lib/virtualenv/buildbot-master/bin/buildbot  stop --clean /home/buildbot/master
  args:
    chdir: /home/buildbot/master


- name: restart buildbot master service
  systemd:
    name: buildbot-master.service
    daemon_reload: yes
    state: restarted
