- name: reconfigure buildbot
  become: yes
  become_user: buildbot
  shell: kill -s HUP $(ps -C buildbot -o pid=)


- name: restart buildbot master service
  systemd:
    name: buildbot-master.service
    daemon_reload: yes
    state: restarted
