- apt:
    name: nginx


- template:
    src: buildbot.nginx.j2
    dest: /etc/nginx/sites-available/buildbot
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  vars:
    tls_enabled: false
  notify: restart nginx


- file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx


- file:
    src: /etc/nginx/sites-available/buildbot
    dest: /etc/nginx/sites-enabled/buildbot
    owner: root
    group: root
    state: link
  notify: restart nginx
