- include_vars:
    file: site_settings.yml
    name: site_settings


- name: setup buildbot-worker group
  group:
    name: buildbot-worker


- name: setup buildbot-worker user
  user:
    name: buildbot-worker
    group: buildbot-worker
    home: /home/buildbot-worker


- name: install golemapp dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - python3
    - python3-venv
    - python3-pip


- name: install buildbot and its requirements
  pip:
    executable: pip3
    name: buildbot-worker
  become_user: buildbot-worker


# NOTE: master address will not be updated once configuration is generated
- name: initialized workspace for the worker
  command:
    /home/buildbot-worker/.local/bin/buildbot-worker create-worker
      /home/buildbot-worker/worker
      {{hostvars[groups['master'][0]]['ec2_private_ip_address']}}
      {{worker_name}}
      {{site_settings.worker_pass}}
    creates=/home/buildbot-worker/worker_{{worker_name}}/
  become_user: buildbot-worker


- name: copy a systemd unit file
  template:
    src: buildbot-worker.service
    dest: /etc/systemd/system/buildbot-worker_{{worker_name}}.service
  notify: restart buildbot worker service


- systemd:
    name: buildbot-worker_{{worker_name}}.service
    daemon_reload: yes
    enabled: yes
    state: started
